apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-ollama-base
  namespace: services
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage-ollama-base
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-ollama-models-llama3
  namespace: services
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage-ollama-models-llama3
  resources:
    requests:
      storage: 15Gi
