apiVersion: v1
kind: Secret
metadata:
  name: s-rabbitmq
  namespace: syrin
type: Opaque
data:
  RABBITMQ_DEFAULT_USER: cmFiYml0bXFzeXJpbg== #-> rabbitmqsyrin
  RABBITMQ_DEFAULT_PASS: U3ZjUmFiQml0TVEwMQ== #-> SvcRabBitMQ01