apiVersion: apps/v1
kind: Deployment
metadata:
  name: de-minio
  namespace: services
spec:
  selector:
    matchLabels:
      app: minio
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: minio
    spec:
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #         - matchExpressions:
      #             - key: "kubernetes.io/hostname"
      #               operator: In
      #               values:
      #                 - "k8s-02"
      #         - matchExpressions:
      #             - key: apps
      #               operator: In
      #               values:
      #                 - services             
      containers:
      - name: minio
        image: minio/minio:RELEASE.2024-10-13T13-34-11Z
        args:
          - minio
          - server
          - /data
          - --console-address
          - :9090
        env:
        - name: MINIO_ROOT_USER 
          valueFrom:
            secretKeyRef:
              name: s-minio
              key: MINIO_ROOT_USER
        - name: MINIO_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: s-minio
              key: MINIO_ROOT_PASSWORD
        ports:
        - name: "9000-minioconso"
          containerPort: 9000
        - name: "9090-minioconso"
          containerPort: 9090
        volumeMounts:
        - name: storage-minio
          mountPath: "/data"
      volumes:
      - name: storage-minio
        hostPath:
          path: /storage/minio # CREATE THIS DIRECTORY /storage/minio IN VM NODE