apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-headless
  namespace: services
  labels:
    app: rabbitmq
    version: "3.12.14"
    component: queue
spec:
  clusterIP: None
  ports:
    - name: epmd
      port: 4369
      protocol: TCP
      targetPort: 4369
    - name: cluster-rpc
      port: 25672
      protocol: TCP
      targetPort: 25672
  selector:
    app: rabbitmq
  type: ClusterIP
  sessionAffinity: None
---
kind: Service
apiVersion: v1
metadata:
  namespace: services
  name: svc-rabbitmq
  labels:
    app: rabbitmq
    version: "3.12.14"
    component: queue
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 15672
      targetPort: 15672
    - name: amqp
      protocol: TCP
      port: 5672
      targetPort: 5672
  selector:
    app: rabbitmq
    component: queue
---
kind: Service
apiVersion: v1
metadata:
  namespace: services
  name: svce-rabbitmq
  labels:
    app: rabbitmq
    version: "3.12.14"
    component: queue
spec:
  type: NodePort
  ports:
    - port: 15672
      nodePort: 30072
      targetPort: 15672
      name: rabbitmq-svce
  selector:
    app: rabbitmq
    component: queue
---
kind: Service
apiVersion: v1
metadata:
  namespace: services
  name: svcet-rabbitmq
  labels:
    app: rabbitmq
    version: "3.12.14"
    component: queue
spec:
  type: NodePort
  ports:
    - port: 5672
      nodePort: 30672
      targetPort: 5672
      name: rabbitmq-svcet
  selector:
    app: rabbitmq
    component: queue
