apiVersion: apps/v1
kind: Deployment
metadata:
  name: de-syrin-make-audio-tts
  namespace: syrin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: syrin-make-audio-tts
      component: syrin
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: syrin-make-audio-tts
        component: syrin
    spec:
      imagePullSecrets:
        - name: s-token-docker-hub
      containers:
        - name: syrin-make-audio-tts
          image: didevlab/poc:syrin_make_audio_tts-1.0.0
          command:
            - "python3"
            - "main.py"
          env:
            - name: TZ
              value: "America/Sao_Paulo"

            - name: RABBITMQ_HOST
              value: "svc-rabbitmq.services.svc.cluster.local"
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_VHOST
              value: "syrin"
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: s-rabbitmq
                  key: RABBITMQ_DEFAULT_USER
            - name: RABBITMQ_PASS
              valueFrom:
                secretKeyRef:
                  name: s-rabbitmq
                  key: RABBITMQ_DEFAULT_PASS
            - name: RABBITMQ_TTL_DLX
              value: "60000"

            - name: MINIO_URL
              value: "svc-minio-api.services.svc.cluster.local"
            - name: MINIO_PORT
              value: "9000"
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: s-minio
                  key: MINIO_ACCESS_KEY
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: s-minio
                  key: MINIO_SECRET_KEY
            - name: MINIO_BUCKET_WORK
              value: "syrin"
           
          volumeMounts:
            - name: syrin-make-audio-tts
              mountPath: /app/main.py
              subPath: main.py
      volumes:
        - name: syrin-make-audio-tts
          configMap:
            name: cm-syrin-make-audio-tts

      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: apps
                    operator: In
                    values:
                      - services
